#! /usr/bin/env bash

set -euo pipefail

function install () {
    raco pkg install
}

function install-deps () {
    raco pks install --auto pollen
}

function web () {
    (
        cd web
        ./Taskfile "$@"
    )
}

function help () {
    echo "Usage: $0 <task> <args>"
    echo 'Tasks:'
    compgen -A function | cat -n
}

function default () {
    help
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
